on:
  workflow_dispatch:
  schedule:
    - cron:  ###

name: AppGWCertDate

env:
  storageaccount_key: ###

jobs:
  deploy-script:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install required PowerShell modules
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name Az -Scope CurrentUser -Repository PSGallery
        

    - name: Login via Az module
      uses: azure/login@v2
      with:
        creds: '###'
        enable-AzPSSession: true 

    - name: Run Azure PowerShell script
      shell: pwsh
      run: |
        ###
